"""PMPML bus route selection and multimodal walk-bus-walk metrics."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from app.calculations.distance import haversine_distance_meters, interpolate_great_circle, polyline_distance_meters
from app.models.route import LocationPoint, RouteLeg, RouteRequest, RouteResponse
from app.models.transit import BusLeg, BusRoute, BusStop
from app.transport.walking import WALKING_SPEED_KMH, WalkingRouter, walking_router

LOGGER = logging.getLogger(__name__)
PROJECT_ROOT = Path(__file__).resolve().parents[2]
NETWORK_PATH = PROJECT_ROOT / "data" / "processed" / "pune_bus_network.json"
WALKING_RADIUS_METERS = 1500.0
BUS_SPEED_KMH = 20.0
STOP_DWELL_MINUTES = 1.0
CO2_GRAMS_PER_PASSENGER_KM = 35.0

# Small built-in safety net for deployments where the data processing script
# has not yet been run. The production seed file is generated by process_gtfs.py.
FALLBACK_STOPS: dict[str, dict[str, Any]] = {
    "swargate": {"id": "seed-swargate", "name": "Swargate", "lat": 18.5018, "lng": 73.8636},
    "laxmi": {"id": "seed-laxmi-narayan", "name": "Laxmi Narayan", "lat": 18.4949, "lng": 73.8614},
    "padmavati": {"id": "seed-padmavati", "name": "Padmavati", "lat": 18.4790, "lng": 73.8620},
    "bharati": {"id": "seed-bharati-vidyapeeth", "name": "Bharati Vidyapeeth", "lat": 18.4606, "lng": 73.8574},
    "katraj": {"id": "seed-katraj", "name": "Katraj", "lat": 18.4575, "lng": 73.8675},
    "kothrud": {"id": "seed-kothrud-depot", "name": "Kothrud Depot", "lat": 18.5071, "lng": 73.8072},
    "karve": {"id": "seed-karve-nagar", "name": "Karve Nagar", "lat": 18.4898, "lng": 73.8190},
    "deccan_gymkhana": {"id": "seed-deccan-gymkhana", "name": "Deccan Gymkhana", "lat": 18.5164, "lng": 73.8400},
    "pmc": {"id": "seed-pmc", "name": "PMC", "lat": 18.5204, "lng": 73.8567},
    "station": {"id": "seed-pune-station", "name": "Pune Station", "lat": 18.5289, "lng": 73.8744},
    "hadapsar": {"id": "seed-hadapsar", "name": "Hadapsar", "lat": 18.5089, "lng": 73.9260},
    "magarpatta": {"id": "seed-magarpatta", "name": "Magarpatta", "lat": 18.5167, "lng": 73.9270},
    "racecourse": {"id": "seed-racecourse", "name": "Racecourse", "lat": 18.4917, "lng": 73.8941},
    "deccan": {"id": "seed-deccan", "name": "Deccan", "lat": 18.5164, "lng": 73.8400},
    "hinjewadi": {"id": "seed-hinjewadi-phase-3", "name": "Hinjewadi Phase 3", "lat": 18.5913, "lng": 73.7389},
    "waje": {"id": "seed-waje", "name": "Waje", "lat": 18.5830, "lng": 73.7510},
    "chandani": {"id": "seed-chandani-chowk", "name": "Chandani Chowk", "lat": 18.5076, "lng": 73.7775},
    "university": {"id": "seed-university-circle", "name": "University Circle", "lat": 18.5362, "lng": 73.8297},
    "shivajinagar": {"id": "seed-shivajinagar", "name": "Shivajinagar", "lat": 18.5308, "lng": 73.8475},
    "viman": {"id": "seed-viman-nagar", "name": "Viman Nagar", "lat": 18.5679, "lng": 73.9143},
    "yerwada": {"id": "seed-yerwada", "name": "Yerwada", "lat": 18.5471, "lng": 73.8787},
    "bund": {"id": "seed-bund-garden", "name": "Bund Garden", "lat": 18.5362, "lng": 73.8833},
}
FALLBACK_ROUTE_STOPS = [
    ("Route 1 · Swargate ↔ Katraj", ["swargate", "laxmi", "padmavati", "bharati", "katraj"]),
    ("Route 2 · Kothrud Depot ↔ Pune Station", ["kothrud", "karve", "deccan_gymkhana", "pmc", "station"]),
    ("Route 3 · Hadapsar ↔ Deccan Gymkhana", ["hadapsar", "magarpatta", "racecourse", "swargate", "deccan"]),
    ("Route 4 · Hinjewadi Phase 3 ↔ PMC", ["hinjewadi", "waje", "chandani", "university", "shivajinagar", "pmc"]),
    ("Route 5 · Viman Nagar ↔ Swargate", ["viman", "yerwada", "bund", "station", "swargate"]),
]


def _fallback_routes() -> list[BusRoute]:
    routes = []
    for number, (name, keys) in enumerate(FALLBACK_ROUTE_STOPS, start=1):
        outbound = [BusStop(**FALLBACK_STOPS[key]) for key in keys]
        inbound = list(reversed(outbound))
        routes.extend([
            BusRoute(route_id=f"seed-route-{number}-out", route_name=name, stops=outbound),
            BusRoute(route_id=f"seed-route-{number}-return", route_name=name, stops=inbound),
        ])
    return routes


class BusRouter:
    """Find the fastest direct seeded/GTFS bus route with walking access legs."""

    def __init__(
        self,
        network_path: Path | str = NETWORK_PATH,
        walking: WalkingRouter | None = None,
        walking_radius_meters: float = WALKING_RADIUS_METERS,
    ) -> None:
        self.network_path = Path(network_path)
        self.walking = walking or walking_router
        self.walking_radius_meters = walking_radius_meters
        self.routes = self._load_routes()

    def _load_routes(self) -> list[BusRoute]:
        try:
            document = json.loads(self.network_path.read_text(encoding="utf-8"))
            routes = [BusRoute.model_validate(route) for route in document.get("routes", [])]
            if routes:
                return routes
        except (OSError, json.JSONDecodeError, ValueError, TypeError) as exc:
            LOGGER.info("Bus network unavailable; using built-in seed corridor data: %s", exc)
        return _fallback_routes()

    @staticmethod
    def _stop_distance(point: LocationPoint, stop: BusStop) -> float:
        return haversine_distance_meters((point.lat, point.lng), (stop.lat, stop.lng))

    @staticmethod
    def _fare(distance_km: float) -> float:
        if distance_km <= 2:
            return 5.0
        if distance_km <= 8:
            return 10.0
        if distance_km <= 14:
            return 15.0
        if distance_km <= 20:
            return 20.0
        return 25.0

    def _select_bus_leg(self, request: RouteRequest) -> tuple[BusLeg, float, float, BusStop, BusStop] | None:
        best: tuple[tuple[float, float, float], BusLeg, float, float, BusStop, BusStop] | None = None
        for route in self.routes:
            for board_index, board_stop in enumerate(route.stops):
                origin_walk_m = self._stop_distance(request.origin, board_stop)
                if origin_walk_m > self.walking_radius_meters:
                    continue
                for alight_index, alight_stop in enumerate(route.stops):
                    if alight_index <= board_index:
                        continue
                    destination_walk_m = self._stop_distance(request.destination, alight_stop)
                    if destination_walk_m > self.walking_radius_meters:
                        continue
                    transit_stops = route.stops[board_index : alight_index + 1]
                    coordinates = [(stop.lat, stop.lng) for stop in transit_stops]
                    transit_m = polyline_distance_meters(coordinates)
                    distance_km = transit_m / 1000.0
                    dwell_count = max(0, len(transit_stops) - 2)
                    duration_min = distance_km / BUS_SPEED_KMH * 60.0 + dwell_count * STOP_DWELL_MINUTES
                    bus_leg = BusLeg(
                        route_name=route.route_name,
                        board_stop=board_stop,
                        alight_stop=alight_stop,
                        distance_km=round(distance_km, 3),
                        duration_min=round(duration_min, 1),
                        fare_inr=self._fare(distance_km),
                        co2_grams=round(distance_km * CO2_GRAMS_PER_PASSENGER_KM, 1),
                        geometry=[[round(stop.lat, 7), round(stop.lng, 7)] for stop in transit_stops],
                    )
                    origin_walk_km = origin_walk_m / 1000.0
                    destination_walk_km = destination_walk_m / 1000.0
                    walk_duration = (origin_walk_km + destination_walk_km) / WALKING_SPEED_KMH * 60.0
                    key = (duration_min + walk_duration, origin_walk_m + destination_walk_m, distance_km)
                    candidate = (key, bus_leg, origin_walk_km, destination_walk_km, board_stop, alight_stop)
                    if best is None or key < best[0]:
                        best = candidate
        return best[1:] if best else None

    def route(self, request: RouteRequest) -> RouteResponse:
        """Return walk-to-stop, bus, and walk-from-stop legs for a journey."""
        selected = self._select_bus_leg(request)
        if selected is None:
            raise ValueError("No direct bus route found within 1.5 km of both locations")
        bus_leg, _, _, board_stop, alight_stop = selected

        walk_to = self.walking.route(RouteRequest(
            origin=request.origin,
            destination=LocationPoint(lat=board_stop.lat, lng=board_stop.lng, label=board_stop.name),
        )).legs[0]
        walk_from = self.walking.route(RouteRequest(
            origin=LocationPoint(lat=alight_stop.lat, lng=alight_stop.lng, label=alight_stop.name),
            destination=request.destination,
        )).legs[0]

        legs = [
            RouteLeg(mode="walking", distance_km=walk_to.distance_km, duration_min=walk_to.duration_min,
                     fare_inr=0.0, co2_grams=0.0, geometry=walk_to.geometry),
            RouteLeg(mode="bus", distance_km=bus_leg.distance_km, duration_min=bus_leg.duration_min,
                     fare_inr=bus_leg.fare_inr, co2_grams=bus_leg.co2_grams, geometry=bus_leg.geometry,
                     route_name=bus_leg.route_name, board_stop=bus_leg.board_stop, alight_stop=bus_leg.alight_stop),
            RouteLeg(mode="walking", distance_km=walk_from.distance_km, duration_min=walk_from.duration_min,
                     fare_inr=0.0, co2_grams=0.0, geometry=walk_from.geometry),
        ]
        return RouteResponse(
            mode="bus",
            total_distance_km=round(sum(leg.distance_km for leg in legs), 3),
            total_duration_min=round(sum(leg.duration_min for leg in legs), 1),
            total_fare_inr=bus_leg.fare_inr,
            total_co2_grams=bus_leg.co2_grams,
            legs=legs,
        )


bus_router = BusRouter()
